params:
  seed: ${...seed}
  algo:
    name: mt_a2c_continuous

  model:
    name: mt_continuous_a2c_logstd

  network:
    name: moore_ppo
    separate: True

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    moore:
      num_experts: 2
      num_layers: 2
      D: 256
      activation: relu
      agg_activation: [Linear, Linear]
      initializer:
        name: xavier_uniform # TODO: connect the value here to actual initializer used
      multi_head: True
    head:
      units: [256]
      activation: elu
      d2rl: False
      initializer:
        name: xavier_uniform # TODO: connect the value here to actual initializer used
    task_encoder:
      units: [128]
      activation: relu
      bias: False
      d2rl: False
      initializer:
        name: xavier_uniform # TODO: connect the value here to actual initializer used

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:mt_moore_SHPPO,${....experiment}} 
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: ${....multi_gpu}
    ppo: True
    mixed_precision: False
    normalize_input: False
    normalize_value: False
    value_bootstrap: True
    clip_actions: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.01
    score_to_win: 10000
    max_epochs: ${resolve_default:3000,${....max_iterations}}
    save_best_after: 200
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.005
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 16384
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.00
    shuffle_data: True